apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runnerdeploy
spec:
  replicas: 1
  template:
    spec:
      repository: luminesoft/github-runner-on-aks
      organization: luminesoft 
      image: ghcr.io/luminesoft/github-runner-on-aks:main
      imagePullSecrets:
      - name: runnersecret